name: update-playwright-snapshots
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-central-1

jobs:
  update:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        pnpm install
        pnpm exec playwright install --with-deps
    - name: Generate new snapshots
      continue-on-error: true
      run: pnpm e2e
    - name: Upload new snapshots
      run: |
        if [ ! -d "tests/__snapshots__" ]; then
          echo "Error: No snapshots were generated"
          exit 1
        fi
        aws s3 sync tests/__snapshots__/ s3://${{ secrets.S3_BUCKET_NAME }}/blog/
